[package]
name = "bench-curl-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cli
clap = { version = "4.0.29", features = ["derive"] }

core ={ path = "../core"}
